<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AwardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data
        DB::table('awards')->delete();
        
        // Get foreign key mappings
        $staffMap = DB::table('staff')->pluck('id', 'staff_id')->toArray();
        $competitionMap = DB::table('competitions')->pluck('id', 'event_name')->toArray();
        $projectMap = DB::table('projects')->pluck('id', 'project_title')->toArray();
        
        // Helper function to parse date from dd-mm-yyyy to Y-m-d
        $parseDate = function($dateStr) {
            if (empty($dateStr)) return null;
            $parts = explode('-', $dateStr);
            if (count($parts) === 3) {
                return $parts[2] . '-' . $parts[1] . '-' . $parts[0];
            }
            return null;
        };
        
        // Helper function to parse amount
        $parseAmount = function($amountStr) {
            if (empty($amountStr)) return null;
            return (float) str_replace(['RM', ','], '', $amountStr);
        };
        
        $awards = [
            [
                'project_id' => $projectMap['TRANSFORMER-BASED MULTIMODAL COMMUNICATION SYSTEM FOR WORD PREDICTION IN APHASIA'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['THE 2ND ARTIFICIAL INTELLIGENCE APPLICATION CHALLENGE BY CHINA-ASEAN INFORMATION HARBOR ELECTRONIC INFORMATION TALENT DEVELOPMENT AND TECHNOLOGY INNOVATION ALLIANCE'] ?? null,
                'staff_id' => $staffMap['01300'] ?? null,
                'award_name' => 'SPECIAL',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('01-07-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['ANTIBACTERIAL SELF-HEALING COATING'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['4TH INTERNATIONAL RESEARCH & INNOVATIVE TECHNOLOGY COMPETITION 2025 (I-RITEC2025)'] ?? null,
                'staff_id' => $staffMap['02610'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('10-07-2025'),
                'amount' => $parseAmount('RM250.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['THE IRON STATUE'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['4TH INTERNATIONAL RESEARCH & INNOVATIVE TECHNOLOGY COMPETITION 2025 (I-RITEC2025)'] ?? null,
                'staff_id' => $staffMap['02610'] ?? null,
                'award_name' => 'BRONZE',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('10-07-2025'),
                'amount' => $parseAmount('RM250.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['ANTIBACTERIAL SELF-HEALING COATING'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['PERTANDINGAN INOVASI ALAM MELAYU ANTARABANGSA 2025 (IMAN25)'] ?? null,
                'staff_id' => $staffMap['02610'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('15-07-2025'),
                'amount' => $parseAmount('RM200.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['ENHANCING ENVIRONMENTAL AWARENESS THROUGH FUNCTIONAL ART: AN IRON STATUE PROJECT'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['PERTANDINGAN INOVASI ALAM MELAYU ANTARABANGSA 2025 (IMAN25)'] ?? null,
                'staff_id' => $staffMap['02610'] ?? null,
                'award_name' => 'SILVER',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('15-07-2025'),
                'amount' => $parseAmount('RM200.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['WORKSHOP TOOL TROLLEY'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['PERTANDINGAN INOVASI ALAM MELAYU ANTARABANGSA 2025 (IMAN25)'] ?? null,
                'staff_id' => $staffMap['02610'] ?? null,
                'award_name' => 'SILVER',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('15-07-2025'),
                'amount' => $parseAmount('RM200.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['FRUITY HONEY GUMMY BERRY'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['INTERNATIONAL SCIENCE AND SOCIAL SCIENCE INNOVATION COMPETITION (ISIC VII 2025) -ONLINE'] ?? null,
                'staff_id' => $staffMap['2719'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('31-07-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['FRUITY HONEY GUMMY BERRY'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['INTERNATIONAL SCIENCE AND SOCIAL SCIENCE INNOVATION COMPETITION (ISIC VII 2025) -ONLINE'] ?? null,
                'staff_id' => $staffMap['2719'] ?? null,
                'award_name' => 'PLATINUM',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('31-07-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['BEWELL - YOUR SMART COMPANION OFR A BETTER SELF-CARE JOURNEY'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['2ND INTERNATIONAL DEVELOPMENT, RESEARCH AND INNOVATION EXHIBITION (IDRIVE\'25)'] ?? null,
                'staff_id' => $staffMap['01678'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('11-08-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['HEARTCARE: AI-DRIVEN MOBILE APPLICATION WITH CARDIOVASCULAR HEALTH ASSISTANT'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['2ND INTERNATIONAL DEVELOPMENT, RESEARCH AND INNOVATION EXHIBITION (IDRIVE\'25)'] ?? null,
                'staff_id' => $staffMap['01678'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('11-08-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['SMART FOOD EXPIRY TRACKER AND AI RECIPE RECOMMENDER'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['2ND INTERNATIONAL DEVELOPMENT, RESEARCH AND INNOVATION EXHIBITION (IDRIVE\'25)'] ?? null,
                'staff_id' => $staffMap['01678'] ?? null,
                'award_name' => 'SILVER',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('11-08-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['NEXT-GEN ACADEMIC INSIGHTS: A HETEROGENEOUS NOSQL GRAPH DATA RETRIEVAL MODEL FOR INSTITUTIONAL MONITORING'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['EKSPO PENYELIDIKAN ANTARABANGSA'] ?? null,
                'staff_id' => $staffMap['1137'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('11-08-2025'),
                'amount' => $parseAmount('RM150.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['MINDSIGHT : FACIAL EMOTION RECOGNITION FOR MENTAL HEALTH MONITORING'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['KUALA LUMPUR INTERNATIONAL INVENTION & INNOVATION SYMPOSIUM 2025, UNIVERSITI TEKNOLOGI MARA (UITM) KELANTAN BRANCH'] ?? null,
                'staff_id' => $staffMap['01300'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('25-08-2025'),
                'amount' => $parseAmount('RM100.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['CROWDVISION : COUNTING PEOPLE IN CROWDED EVENTS VIA COMPUTER VISION'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['KUALA LUMPUR INTERNATIONAL INVENTION & INNOVATION SYMPOSIUM 2025, UNIVERSITI TEKNOLOGI MARA (UITM) KELANTAN BRANCH'] ?? null,
                'staff_id' => $staffMap['01300'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('25-08-2025'),
                'amount' => $parseAmount('RM100.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['SAFER CLASS : SMART ATTENDANCE SYSTEM USING FACE RECOGNITION IN CLASSROOM'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['KUALA LUMPUR INTERNATIONAL INVENTION & INNOVATION SYMPOSIUM 2025, UNIVERSITI TEKNOLOGI MARA (UITM) KELANTAN BRANCH'] ?? null,
                'staff_id' => $staffMap['01300'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('25-08-2025'),
                'amount' => $parseAmount('RM100.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['TOPSIS-BASED INNOVATIVE GOAT MILK QUALITY CLASSIFICATION USING MULTI-ARRAY SENSOR TECHNOLOGY'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['HARI INOVASI NEGERI MELAKA'] ?? null,
                'staff_id' => $staffMap['02777'] ?? null,
                'award_name' => 'BRONZE',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('25-09-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['AQUA PREDATOR FISH CONTROL AND BIO-CONVERSION FOR AGRIBUSINESS'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['HARI INOVASI NEGERI MELAKA'] ?? null,
                'staff_id' => $staffMap['2725'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('25-09-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['AQUA PREDATOR FISH CONTROL AND BIO-CONVERSION FOR AGRIBUSINESS'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['HARI INOVASI NEGERI MELAKA'] ?? null,
                'staff_id' => $staffMap['2725'] ?? null,
                'award_name' => 'SPECIAL',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('25-09-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['PROTOTYPE OF AUTISM EARLY DIAGNOSIS THROUGH HANDWRITING'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['EKSPO PENYELIDIKAN ANTARABANGSA'] ?? null,
                'staff_id' => $staffMap['02638'] ?? null,
                'award_name' => 'SILVER',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('25-09-2025'),
                'amount' => $parseAmount('RM20.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['FOODMIND:SMART FOOD EXPIRY TRACKER AND AI RECIPE RECOMMENDER'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['WORLD INOVATION IN STEM COMPETITION 2025'] ?? null,
                'staff_id' => $staffMap['01678'] ?? null,
                'award_name' => 'SILVER',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('27-09-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['HEARTCARE: AI-DRIVEN MOBILE APPLICATION WITH CARDIOVASCULAR HEALTH ASSISTANT'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['WORLD INOVATION IN STEM COMPETITION 2025'] ?? null,
                'staff_id' => $staffMap['01678'] ?? null,
                'award_name' => 'SILVER',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('27-09-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['UTEM TEAM'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['RBN-AUTOMOBILE ROBONEO 2025'] ?? null,
                'staff_id' => $staffMap['01300'] ?? null,
                'award_name' => 'SPECIAL',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('04-10-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['GUESS THE LEARNING TYPE: AI?ENHANCED GAMIFIED LEARNING KIT FOR MACHINE LEARNING EDUCATION'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['EKSPO PENYELIDIKAN ANTARABANGSA'] ?? null,
                'staff_id' => $staffMap['01043'] ?? null,
                'award_name' => 'SILVER',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('07-10-2025'),
                'amount' => $parseAmount('RM350.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['GUESS THE LEARNING TYPE: AI?ENHANCED GAMIFIED LEARNING KIT FOR MACHINE LEARNING EDUCATION'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['PERTANDINGAN INOVASI IPTA/S'] ?? null,
                'staff_id' => $staffMap['2592'] ?? null,
                'award_name' => 'SILVER',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('07-10-2025'),
                'amount' => $parseAmount('RM350.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['PROTOTYPE OF AUTISM EARLY DIAGNOSIS THROUGH HANDWRITING'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['INTERNATIONAL TECHNOLOGY TELENT COMPETITION'] ?? null,
                'staff_id' => $staffMap['2638'] ?? null,
                'award_name' => 'BRONZE',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('09-10-2025'),
                'amount' => $parseAmount('RM0.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'project_id' => $projectMap['BRINGING ATOMS TO LIFE: AR-BASED LEARNING IN MICROELECTRONICS'] ?? null,
                'product_id' => null,
                'competition_id' => $competitionMap['XCIPTA 2025'] ?? null,
                'staff_id' => $staffMap['2195'] ?? null,
                'award_name' => 'GOLD',
                'award_level' => 'Individual',
                'award_type' => 'Exhibition',
                'award_date' => $parseDate('10-10-2025'),
                'amount' => $parseAmount('RM250.00'),
                'evidence_document' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($awards as $award) {
            DB::table('awards')->insert($award);
        }
    }
}
